### ISSUE TITLE
ckb-next mailing list

### ISSUE THREAD

**Issue by ghost** [frickler24/ckb-next#8]
Hello,

you seem to be active on GitHub, however you never responded on any messages sent on both emails belonging to you (public one on your website and private one looked up on the screenshot (sorry, I wanted to contact you anyway)) regarding mailing list. Is there any specific reason why you ignore these messages or you just didn't have time to check inbox?

Sorry for opening an issue here, but this is the last way I can think of to get in touch with you.

**Comment by frickler24** [comment]
Thanks for this, I found your emails in my spam filter!

**Comment by ghost** [comment]
Please, add me to the contact list, I also sent you a new PGP key [public.key.txt](https://github.com/frickler24/ckb-next/files/984061/public.key.txt) as I don't have the access to the one you've encrypted the message for. I'm attaching it here too. Please, resend me the message re-encrypted with this key.

Or you can directly import it:
```
gpg --keyserver pgp.mit.edu --recv-keys AB19EE86E81A6023
```

**Comment by frickler24** [comment]
Done :-)
